### PR TITLE
fix: update ga4gh.vrs version + add back VRS type anno in models

### LINKED ISSUE #91: Add back missing response models to openapi.json
Split off from https://github.com/biocommons/anyvar/issues/85

Same underlying problem as https://github.com/cancervariants/variation-normalization/issues/543

Changed the response models to return `Dict` instead of the types from `ga4gh.vrs.models`.  This allows the full, dereferenced VRS object to be returned from the API endpoints instead of the version produced by the serialization logic embedded in the model hierarchy.

### PR DESCRIPTION
**Pull request by korikuzma**
close #91

### CODE REVIEW

**Review by jsstevenson — APPROVED** [review]
I think this fix also lets us revert the `model_dump` calls in the API responses?

```python
    if location:
        return {"location": location.model_dump(exclude_none=True)}
```

**Comment by korikuzma** [comment]
I removed my anyvar container, so I didn't test the last commit. Will come back to this later to test and request review afterwards.

**Review by ehclark — APPROVED** [review]
Added an additional change to the response schema to get the unit tests to pass.  The responses for the register endpoints should return a model object if the call to model_dump() is removed.

**Comment by korikuzma** [comment]
@ehclark thank you!

**Pull request merged**
